# -*- mode:python -*-

# Copyright (c) 2021 Huawei International
# Copyright (c) 2022 EXAscale Performance SYStems (EXAPSYS)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Import('*')

SimObject('HiFive.py', sim_objects=['HiFive', 'GenericRiscvnommuPciHost'],
          tags='riscvnommu isa')
#SimObject('LupV.py', sim_objects=['LupV'], tags='riscvnommu isa')
SimObject('Clint.py', sim_objects=['Clint'], tags='riscvnommu isa')
SimObject('PlicDevice.py', sim_objects=['PlicIntDevice'], tags='riscvnommu isa')
SimObject('Plic.py', sim_objects=['Plic'], tags='riscvnommu isa')
SimObject('RTC.py', sim_objects=['RiscvnommuRTC'], tags='riscvnommu isa')
SimObject('RiscvnommuVirtIOMMIO.py', sim_objects=['RiscvnommuMmioVirtIO'],
    tags='riscvnommu isa')

#DebugFlag('Clint', tags='riscvnommu isa')
#DebugFlag('Plic', tags='riscvnommu isa')
#DebugFlag('VirtIOMMIO', tags='riscvnommu isa')

Source('pci_host.cc', tags='riscvnommu isa')

Source('hifive.cc', tags='riscvnommu isa')
#Source('lupv.cc', tags='riscvnommu isa')
Source('clint.cc', tags='riscvnommu isa')
Source('plic_device.cc', tags='riscvnommu isa')
Source('plic.cc', tags='riscvnommu isa')
Source('rtc.cc', tags='riscvnommu isa')
Source('vio_mmio.cc', tags='riscvnommu isa')
