# -*- mode:python -*-

# Copyright (c) 2006 The Regents of The University of Michigan
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import sys

Import('*')

#if env['CONF']['TARGET_ISA'] != 'null':
SimObject('CapstoneFUPool.py', sim_objects=['CapstoneFUPool'], tags='riscvcapstone isa')
#SimObject('CapstoneO3NodeController.py', sim_objects=['CapstoneO3NodeController'], tags='riscvcapstone isa')
SimObject('CapstoneFuncUnitConfig.py', sim_objects=[], tags='riscvcapstone isa')
SimObject('CapstoneBaseO3CPU.py', sim_objects=['CapstoneBaseO3CPU'], enums=[
    'CapstoneSMTFetchPolicy', 'CapstoneSMTQueuePolicy', 'CapstoneCommitPolicy'], tags='riscvcapstone isa')

Source('commit.cc', tags='riscvcapstone isa')
Source('cpu.cc', tags='riscvcapstone isa')
Source('decode.cc', tags='riscvcapstone isa')
Source('dyn_inst.cc', tags='riscvcapstone isa')
Source('fetch.cc', tags='riscvcapstone isa')
Source('free_list.cc', tags='riscvcapstone isa')
Source('fu_pool.cc', tags='riscvcapstone isa')
Source('iew.cc', tags='riscvcapstone isa')
Source('inst_queue.cc', tags='riscvcapstone isa')
Source('lsq.cc', tags='riscvcapstone isa')
Source('lsq_unit.cc', tags='riscvcapstone isa')
Source('mem_dep_unit.cc', tags='riscvcapstone isa')
Source('regfile.cc', tags='riscvcapstone isa')
Source('rename.cc', tags='riscvcapstone isa')
Source('rename_map.cc', tags='riscvcapstone isa')
Source('rob.cc', tags='riscvcapstone isa')
Source('scoreboard.cc', tags='riscvcapstone isa')
Source('store_set.cc', tags='riscvcapstone isa')
Source('thread_context.cc', tags='riscvcapstone isa')
Source('thread_state.cc', tags='riscvcapstone isa')
#Source('node_controller.cc', tags='riscvcapstone isa')
Source('refcount_buffer.cc', tags='riscvcapstone isa')
Source('node_commands.cc', tags='riscvcapstone isa')
Source('ncq.cc', tags='riscvcapstone isa')
Source('ncq_unit.cc', tags='riscvcapstone isa')

#DebugFlag('CommitRate')
#DebugFlag('IEW')
#DebugFlag('IQ')
#DebugFlag('LSQ')
#DebugFlag('LSQUnit')
#DebugFlag('MemDepUnit')
#DebugFlag('O3CPU')
#DebugFlag('ROB')
#DebugFlag('Rename')
#DebugFlag('Scoreboard')
#DebugFlag('StoreSet')
#DebugFlag('Writeback')

#CompoundFlag('O3CPUAll', [ 'Fetch', 'Decode', 'Rename', 'IEW', 'Commit',
    #'IQ', 'ROB', 'FreeList', 'LSQ', 'LSQUnit', 'StoreSet', 'MemDepUnit',
    #'DynInst', 'O3CPU', 'Activity', 'Scoreboard', 'Writeback' ])

SimObject('CapstoneBaseO3Checker.py', sim_objects=['CapstoneBaseO3Checker'], tags='riscvcapstone isa')
Source('checker.cc', tags='riscvcapstone isa')
