#!/bin/bash

# Copyright (c) 2023 National University of Singapore
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

print_prompt() {
    echo "#################### "$1" ####################"
}

WORKSPACE="$(pwd)"
SPEC_DIR="$WORKSPACE"/spec
INTERPLIB_DIR="$WORKSPACE"/tests/capstone
SPECKLE_DIR="$WORKSPACE"/tests/capstone/speckle
SPEC_BENCHMARK_DIR="$SPECKLE_DIR"/build/overlay/intspeed

if [ ! -d  "$SPEC_DIR" ]; then
    echo "Missing SPEC directory!"
    exit 1
fi

print_prompt "Building interposition library"
cd "$INTERPLIB_DIR"
make

cd "$SPECKLE_DIR"
./gen-configs.sh "$INTERPLIB_DIR"

export RISCV="$RISCV_TOOLCHAIN"

print_prompt "Building SPEC for Capstone"
SPEC_DIR="$SPEC_DIR" ./capstone.sh --genCommands --suite intspeed --input ref
SPEC_DIR="$SPEC_DIR" ./capstone.sh --compile --suite intspeed --input ref

print_prompt "Building SPEC for RISC-V"
SPEC_DIR="$SPEC_DIR" ./gen_binaries.sh --genCommands --suite intspeed --input ref
SPEC_DIR="$SPEC_DIR" ./gen_binaries.sh --compile --suite intspeed --input ref
