#!/bin/bash

# Copyright (c) 2023 National University of Singapore
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

print_prompt() {
    echo "#################### "$1" ####################"
}

CURDIR="$(pwd)"
TEST_DIR="tests/capstone/o3"

NTHREADS=$(nproc)
NTHREADS_TO_USE=$(expr $NTHREADS / 4)
if [ "$NTHREADS_TO_USE" -eq 0 ]; then
    NTHREADS_TO_USE=1
fi

GEM5=$(pwd)/build/RISCVCapstone/gem5.opt
GEM5_CONFIG=$(pwd)/configs/capstone/fast-forward.py


build_all() {
    # release build
    cd "$CURDIR"

    print_prompt "Starting Release Build"
    if scons "$1" -j $NTHREADS_TO_USE --linker=mold $BUILD_FLAGS < /dev/null; then
        print_prompt "Release Build Complete"
    else
        print_prompt "Release Build Failed"
        exit 1
    fi
    
    # TODO: we also need to build the original gem5 model for comparison
}

BUILD_FLAGS=""
GEM5_CONFIG_FLAGS=""

print_prompt "Building RISCVCapstone"
build_all "build/RISCVCapstone/gem5.opt"

print_prompt "Building RISCVNoMMU"
build_all "build/RISCVNoMMU/gem5.opt"
