#!/bin/bash

# Copyright (c) 2023 National University of Singapore
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

WORKSPACE="$(pwd)"

function run_workload() {
    if [ -z "$GEM5_SKIP" ]; then
        GEM5_SKIP=10000000000
    fi

    if [ -z "$GEM5_LIM" ]; then
        GEM5_LIM=1000000000
    fi

    if [ -z "$GEM5_NCACHE" ]; then
        GEM5_NCACHE="8kB"
    fi
    
    "$WORKSPACE"/build/RISCVCapstone/gem5.opt --outdir=${GEM5_OUT} $GEM5_FLAGS \
        "$WORKSPACE"/configs/capstone/fast-forward.py \
        --skip=$GEM5_SKIP --lim=$GEM5_LIM --ncache-size=$GEM5_NCACHE -- $@
}

OUTPUT_DIR="$WORKSPACE"/outputs/capstone
BENCHMARK_DIR="$WORKSPACE"/tests/capstone/speckle/build/overlay/intspeed
RUN_SCRIPT_NAME="run_capstone_workload"

mkdir -p "$OUTPUT_DIR"

source "$WORKSPACE"/docker-scripts/run-all-benchmarks.sh

if [ "$1" = "--multiproc" ]; then
    BENCHMARK_MULTIPROC="Y"
    run_all_benchmarks
else
    BENCHMARK_MULTIPROC="N"
    if [ -n "$1" ]; then
        run_benchmark "$1" "$2"
    else
        run_all_benchmarks
    fi
fi
